name: Regenerate PluginMaster
on: [push]

jobs:
  generate:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    name: Regenerate PluginMaster
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - name: Run generator
        run: .\Make-PluginMaster.ps1
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Regenerate PluginMaster" -a
      - name: Push changes
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
